import "../globals.css";
import styles from "./layout.module.css";
import localFont from 'next/font/local';
import { dir } from 'i18next'
import {languages, languageNames} from "@/i18n/configs";
import TopNavigationBar from "@/components/server/TopNavigationBar";
import Footer from "@/components/server/Footer";

const satoshiVariable = localFont({ src: '../../assets/fonts/Satoshi/Satoshi-Variable.woff2' });

const metadata = {
    title: "Henry's Space",
    description: "Generated by create next app",
};

const generateStaticParams = async () => {
    return languages.map(lang => ({lang}));
}

const RootLayout = ({ children, params }) => {

    const { lang } = params;

    return (
        <html lang={lang} dir={dir(lang)}>
            <body className={satoshiVariable.className}>
                <header className={styles.header}>
                    <TopNavigationBar lang={lang} />
                </header>
                <main className={styles.main}>
                    {children}
                </main>
                <footer className={styles.footer}>
                    <Footer lang={lang} />
                </footer>
            </body>
        </html>
    );
};

export { metadata, generateStaticParams};

export default RootLayout;