import "./globals.css";
import styles from "./layout.module.css";
import localFont from 'next/font/local';
import Link from "next/link";
import Image from "next/image";

const satoshiVariable = localFont({ src: '../assets/fonts/Satoshi/Satoshi-Variable.woff2' });

const metadata = {
    title: "Henry's Space",
    description: "Generated by create next app",
};

const RootLayout = ({ children }) => {

    const navItems = [
        {
            title: "Home",
            url: "/"
        },
        {
            title: "Resume",
            url: "/resume"
        },
        {
            title: "Projects",
            url: "/projects"
        },
        {
            title: "Blog",
            url: "/blogs"
        },
        {
            title: "Contact",
            url: "/contact"
        }
    ];

    return (
        <html lang="en">
            <body className={satoshiVariable.className}>

                <header className={styles.header}>
                    <div className={styles.logo}>
                        {/*<Image src="/assets/images/logo.svg" alt="logo" width={33} height={24}/>*/}
                        <h1>{metadata.title}</h1>
                    </div>
                    <nav className={styles.nav}>
                        {
                            navItems.map((item, index) => (
                                <span key={index}>
                                    <Link href={item.url} key={index}>
                                        {item.title}
                                    </Link>
                                    {
                                        index < navItems.length - 1 && <>&nbsp;&nbsp;</>
                                    }
                                </span>
                            ))
                        }
                    </nav>
                </header>

                <main className={styles.main}>
                    {children}
                </main>

                <footer className={styles.footer}>
                    <section className={styles.contact}>
                        <div>
                            <h5>Email</h5>
                            <Link href="mailto:henry.k.h.hung@gmail.com">henry.k.h.hung@gmail.com</Link>
                        </div>
                        <div>
                            <h5>Location</h5>
                            <span>Hong Kong / Shanghai</span>
                        </div>
                        <div>
                            <h5>Social</h5>
                            <Link href="https://linkedin.com/in/hungkahing">LinkedIn</Link>
                            &nbsp;|&nbsp;
                            <Link href="https://github.com/Henryyy-Hung">GitHub</Link>
                        </div>
                    </section>

                    <section className={styles.copyright}>
                        <p>© 2024 by Henry Hung - All Rights Reserved</p>
                    </section>
                </footer>
            </body>
        </html>
    );
};

export { metadata };

export default RootLayout;